update pre-push

diff --git a/_infra/hooks/pre-push b/_infra/hooks/pre-push
--- a/_infra/hooks/pre-push
+++ b/_infra/hooks/pre-push
@@ -1,9 +1,11 @@
 #!/bin/bash
 
-echo "⬆️ Pushing changes for submodules..."
-git submodule foreach --recursive '
-  echo "⬆️ Pushing $name...";
-  branch=$(git rev-parse --abbrev-ref HEAD);
-  git push origin $branch || echo "⚠️ Failed to push $name.";
+echo "🚀 Pushing changes for submodules..."
+
+git submodule foreach --recursive --quiet '
+    echo "⏳ Pushing $name...";
+    branch=$(git rev-parse --abbrev-ref HEAD);
+    git push origin $branch || echo "⚠️ Failed to push $name.";
 '
+
 echo "✅ All submodules pushed!"
